app.py
from flask import Flask

from routes.downloader import download
from routes.thumbnails import thumbnail


def create_app():
    app = Flask(__name__)
    app.register_blueprint(thumbnail)
    app.register_blueprint(download)

    return app

main.py
from app import create_app


app = create_app()


if __name__ == '__main__':
    app.run(debug=True, port=5000)

routes/downloader.py
from flask import Blueprint, render_template, request, jsonify
from pytube import YouTube, Caption
import re

download = Blueprint("download", __name__, url_prefix="/download")


@download.route("/audio", methods=["GET", "POST"])
def audio():
    if request.method == "POST":
        payload = request.get_json()
        if video_id := payload.get("video_id"):
            yt = YouTube(url=f"https://youtube.com/watch?v={video_id}", use_oauth=False, allow_oauth_cache=True)
            yt.bypass_age_gate()
            audio_stream = yt.streams.filter(only_audio=True).first()
            return jsonify({"url": audio_stream.url, "size": audio_stream.filesize_mb})
    return render_template("download.html")


@download.route("/video", methods=["GET", "POST"])
def video():
    if request.method == "POST":
        payload = request.get_json()
        if video_id := payload.get("video_id"):
            yt = YouTube(url=f"https://youtube.com/watch?v={video_id}")
            yt.bypass_age_gate()
            video_streams_list = yt.streams

            #Process Streams With Audio
            av_streams = [streams for streams in video_streams_list
                             if (streams.includes_video_track and streams.includes_audio_track)]
            av_streams = av_streams[::-1]  # Reversing To Get Highest To The Lowest resolution

            # Process Streams Without Audio
            only_vid_streams = [streams for streams in video_streams_list
                                if streams.includes_video_track and not streams.includes_audio_track]

            with_audio, no_audio= [], []
            for stream in av_streams:
                video_data = {"res": stream.resolution,
                              "size": f"{stream.filesize / (1024 * 1024):.2f} MB",
                              "url": stream.url}
                with_audio.append(video_data)

            for stream in only_vid_streams:
                video_data = {"res": stream.resolution,
                              "size": f"{stream.filesize / (1024 * 1024):.2f} MB",
                              "url": stream.url}
                no_audio.append(video_data)

            video_dict = {"av": with_audio, "ov": no_audio}
            return jsonify(video_dict)

    return render_template("download_video.html")

@download.route("/captions", methods=["GET", "POST"])
def trim_audio():
    if request.method == "POST":
        payload = request.get_json()
        if video_id := payload.get("video_id"):
            yt = YouTube(url=f"https://youtube.com/watch?v={video_id}")
            yt.bypass_age_gate()
            video_streams_list = stream = yt.streams.get_highest_resolution()

            # Step 5: Generate the trimmed stream URL
            trimmed_stream_url = f"{stream.url}&begin={10}&end={20}"
            print("Trimmed Stream URL:", trimmed_stream_url)

    if video_id := request.args.get("video_id"):
        yt = YouTube(url=f"https://youtube.com/watch?v={video_id}")
        yt.bypass_age_gate()
        if captions := yt.captions.all():
            # Step 5: Select the first available caption track (assuming it's in English)
            caption = captions[0]  # 'a.en' represents English captions, you can modify it as needed

            # Step 6: Download the captions
            caption_text = caption.generate_srt_captions()
            print(caption_text)
            return caption_text

routes/thumbnails.py
from flask import Blueprint, render_template, request, Response
import requests
thumbnail = Blueprint("thumbnail", __name__, url_prefix="/")


@thumbnail.route("/")
def landing():
    if url := request.args.get("url"):
        print(url)
        try:
            response = requests.get(url, timeout=10)
            return Response(response.content, mimetype='image/jpeg', headers={'Content-Disposition': 'attachment;filename=image.jpg'})
        except Exception:
            return

    return render_template("index.html")

templates/download.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YouTube Audio Downloader</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
    <script type="text/javascript" id="www-widgetapi-script" src="https://www.youtube.com/s/player/6ed0d907/www-widgetapi.vflset/www-widgetapi.js" async=""></script>
  <script src="https://www.youtube.com/iframe_api"></script>

  </head>
  <body>

<header >
  <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-center">
    <div class="container justify-content-center">
      <a class="navbar-brand" href="{{ url_for('thumbnail.landing') }}">
        <img src="/static/TubeTool.svg" width="150" height="50" alt="Logo">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link"  href="{{url_for('thumbnail.landing')}}">Thumbnail Download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{{url_for('download.audio')}}">Audio Download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('download.video')}}">Video Download</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>
<main>
  <div class="container d-flex justify-content-center align-items-center" style=" height: 20vh;max-width: 1920px;">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Youtube Audio Downloader</h1>
        <p>Please Enter The YouTube Link</p>
        <div class="d-flex">
          <input class="form-control me-2" id="yt_url" type="search" placeholder="Search" aria-label="Search" required>
          <button class="btn btn-outline-success d-flex" id="search_audio_btn" type="submit"> ⬇️Audio</button>
        </div>
      </div>
    </div>
  </div>

  <script>
const search_audio_btn = document.getElementById("search_audio_btn");
search_audio_btn.addEventListener("click", function() {
	event.preventDefault();

	const yt_url = document.getElementById("yt_url").value;
	const downloadBtn = document.getElementById("download_btn");
	const downloadSuccessBtn = document.getElementById("download_btn_success");
	const youtubeVideo = document.getElementById("youtube-video");


	const res = yt_url.match(/(?:https?:\/{2})?(?:w{3}\.)?youtu(?:be)?\.(?:com|be)(?:\/watch\?v=|\/)([^\s&]+)/)
	if (res == undefined) {
		alert("Please check the URL you have entered");
	}
	const videoId = res[1];
	console.log(videoId)
	const payload = {
		video_id: videoId
	};
	youtubeVideo.src = `https://www.youtube.com/embed/${videoId}`;
	downloadSuccessBtn.classList.remove("d-none");
	search_audio_btn.disabled = true;
	search_audio_btn.innerHTML = '<span class="spinner-border text-warning" role="status" aria-hidden="true"></span> Loading';
	downloadSuccessBtn.classList.add("d-none");
	downloadBtn.removeAttribute("href");


	// Make the POST request
	fetch("{{url_for('download.audio')}}", {
			method: "POST",
			headers: {
				"Content-Type": "application/json"
			},
			body: JSON.stringify(payload)
		})
		.then(response => {
			if (response.ok) {
				return response.json();
			} else {
				console.error("Error downloading audio:", response.status);
			}
		})
		.then(data => {
			search_audio_btn.disabled = false;
			search_audio_btn.innerHTML = "⬇️ Audio";
			downloadBtn.setAttribute("href", data.url);
			downloadBtn.innerHTML = `️🖐👉Download✅ (${data.size} MB)`;
			downloadSuccessBtn.classList.remove("d-none");


		})
		.catch(error => {
			console.error("Error downloading audio:", error);
		});

});
  </script>

<div class="container justify-content-center align-items-center" id="show_yt_audio">
  <div class="row">

    <div class="d-flex justify-content-center align-items-center video-container">
  <iframe id="youtube-video" width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allowfullscreen></iframe>
</div>

    <div id="download_btn_success" class="d-flex my-3 justify-content-center align-items-center d-none">
     <a class="btn btn-success btn-lg" id="download_btn" target="_blank" type="button">🖐️👉Download✅</a>
    </div>


</div>

</div>

</main>


    <footer>
      <!-- Your footer content goes here -->
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

templates/download_video.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>YouTube Video Downloader</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://www.youtube.com/iframe_api"></script>
    <style>
      .flex-container {
      display: flex;
      align-items: center;
      justify-content: center;
      }
    </style>
  </head>
  <body>
    <header >
      <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-center">
        <div class="container justify-content-center">
          <a class="navbar-brand" href="{{ url_for('thumbnail.landing') }}">
          <img src="/static/TubeTool.svg" width="150" height="50" alt="Logo">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link"  href="{{url_for('thumbnail.landing')}}">Thumbnail Download</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('download.audio')}}">Audio Download</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href="{{url_for('download.video')}}">Video Download</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container d-flex justify-content-center align-items-center" style=" height: 20vh;max-width: 1920px;">
        <div class="row">
          <div class="col-md-12 text-center">
            <h1>Youtube Video Downloader</h1>
            <p>Please Enter The YouTube Link</p>
            <div class="d-flex">
              <input class="form-control me-2" id="yt_url" type="search" placeholder="Enter Youtube Video URL" aria-label="Search" required>
              <button class="btn btn-outline-success d-flex" id="search_video_btn" type="submit"> ⬇Video</button>
            </div>
          </div>
        </div>
      </div>
      <script>
        const search_video_btn = document.getElementById("search_video_btn");

        search_video_btn.addEventListener("click", function() {
        	event.preventDefault();

            const video_div = document.getElementById("video_div");
        	const yt_url = document.getElementById("yt_url").value;
        	const youtubeVideo = document.getElementById("youtube-video");
            const tableBody = document.getElementById('tableBody');
            const tableBody_no_audio = document.getElementById('tableBody_no_audio');
            tableBody.innerHTML = ""
            tableBody_no_audio.innerHTML = ""
            video_div.classList.add("d-none")

        	const res = yt_url.match(/(?:https?:\/{2})?(?:w{3}\.)?youtu(?:be)?\.(?:com|be)(?:\/watch\?v=|\/)([^\s&]+)/)
        	if (res == undefined) {
        		alert("Please check the URL you have entered");
        	}
        	const videoId = res[1];
        	console.log(videoId)
        	const payload = {
        		video_id: videoId
        	};
        	youtubeVideo.src = `https://www.youtube.com/embed/${videoId}`;
        	search_video_btn.disabled = true;
        	search_video_btn.innerHTML = '<span class="spinner-border text-warning" role="status" aria-hidden="true"></span> Loading';

        	fetch("{{url_for('download.video')}}", {
        			method: "POST",
        			headers: {"Content-Type": "application/json"},
        			body: JSON.stringify(payload)
        		})
        		.then(response => {
        			if (response.ok) {
        				return response.json();
        			} else {
        				console.error("Error downloading audio:", response.status);
        			}
        		})
        		.then(data => {
        		    const av = data.av
        		    const ov = data.ov
        			search_video_btn.disabled = false;
        			search_video_btn.innerHTML = "⬇Video";
        			createElements(av, tableBody);
        			createElements(ov, tableBody_no_audio);
        			video_div.classList.remove('d-none');
        		})
        		.catch(error => {
        			console.error("Error downloading audio:", error);
        		});

        });

        function createElements(data, tableBody) {
              data.forEach(item => {
              const tr = document.createElement("tr");
              const td1 = document.createElement("td");
              td1.textContent = item.res;

              const td2 = document.createElement("td");
              td2.textContent = item.size;
              const td3 = document.createElement("td");
              const button = document.createElement("button");
              button.classList.add("btn", "btn-success", "btn-sm");
              button.textContent = "Download";
              button.onclick = function() {
                myFunction(item.url);
              };

              td3.appendChild(button);
              tr.appendChild(td1);
              tr.appendChild(td2);
              tr.appendChild(td3);
              tableBody.appendChild(tr);
              });
            }

            function myFunction(url) {
              window.open(url, '_blank');
              }


      </script>
      <div class="container justify-content-center align-items-center" id="show_yt_audio">
        <div class="row">
          <div class="d-flex justify-content-center align-items-center video-container my-3">
            <iframe id="youtube-video" width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="YouTube" allowfullscreen></iframe>
          </div>
          <div id="video_div" class="d-none">
            <div class="card">
              <h5 class="card-header text-center">Video With Audio✅🎵</h5>
              <div class="container-sm text-center" style="max-width: 600px;">
                <div class="card">
                  <div class="table-responsive">
                    <table class="table table-hover table-sm table-striped">
                      <thead>
                        <tr>
                          <th>Resolution</th>
                          <th>Size</th>
                          <th>Download</th>
                        </tr>
                      </thead>
                      <tbody id="tableBody">
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <div class="card my-3">
              <h5 class="card-header text-center">Video With No Audio❌🎵</h5>
              <div class="container-sm text-center" style="max-width: 600px;">
                <div class="card">
                  <div class="table-responsive">
                    <table class="table table-hover table-sm table-striped">
                      <thead>
                        <tr>
                          <th>Resolution</th>
                          <th>Size</th>
                          <th>Download</th>
                        </tr>
                      </thead>
                      <tbody id="tableBody_no_audio">
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </main>
    <footer>
      <!-- Your footer content goes here -->
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TubeTools: Youtube Thumbnail Downloader</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">

  </head>
  <body>

<header >
  <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-center">
    <div class="container justify-content-center">
      <a class="navbar-brand" href="{{ url_for('thumbnail.landing') }}">
        <img src="/static/TubeTool.svg" width="150" height="50" alt="Logo">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('thumbnail.landing')}}">Thumbnail Download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('download.audio')}}">Audio Download</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('download.video')}}">Video Download</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>




<main>

  <div class="container d-flex justify-content-center align-items-center" style="height: 30vh; max-width: 1920px;">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Youtube Thumbnail Downloader</h1>
        <p>Please Enter The YouTube Link</p>
        <div class="d-flex">
          <input class="form-control me-2" id="yt_url" type="search" placeholder="Search" aria-label="Search" required>
          <button class="btn btn-success" id="search_btn" type="submit">Search</button>
        </div>
      </div>
    </div>
  </div>

<div class="container justify-content-center align-items-center d-none" id="show_yt_img">
  <div class="row">
    <div class="col-md-7 my-2" id="card1">
      <div class="text-center">
      <h5>HD Image (1280x720)</h5>
      <button type="button" class="btn btn-primary btn-sm" id="hd_img_btn">Download HD Thumbnail</button>
      </div>
      <div class="card">
        <img class="img-fluid w-1280 h-720" id="hd_img" src="/static/TubeTool.svg" alt="Card image cap">
      </div>
    </div>

    <div class="col-md-5 my-2" id="card2">
      <div class="text-center">
      <h5>SD Image (640x480)</h5>
      <button type="button" class="btn btn-primary btn-sm" id="sd_img_btn">Download SD Thumbnail</button>
      </div>
      <div class="card">
        <img class="img-fluid w-640 h-480" id="sd_img" src="/static/TubeTool.svg" alt="Card image cap">
      </div>
    </div>

    <div class="col-md-5 my-2" id="card3">
      <div class="text-center">
      <h5>Normal Image (480x360)</h5>
      <button type="button" class="btn btn-primary btn-sm" id="normal_img_btn">Download (480x360)</button>
      </div>
      <div class="card">
        <img class="img-fluid w-480 h-360" id="normal_img1" src="/static/TubeTool.svg" alt="Card image cap">
      </div>
    </div>

    <div class="col-md-4 my-2" id="card4">
      <div class="text-center">
      <h5>Normal Image (320x180)</h5>
      <button type="button" class="btn btn-primary btn-sm" id="normal2_img_btn">Download Normal Img</button>
      </div>
      <div class="card">
        <img class="img-fluid w-320 h-180" id="normal_img2" src="/static/TubeTool.svg" alt="Card image cap">
      </div>
    </div>

    <div class="col-md-3 my-2" id="card5">
      <div class="text-center">
      <h5>Normal Image (120x90)</h5>
      <button type="button" class="btn btn-primary btn-sm" id="normal3_img_btn">Download Img</button>
      </div>
      <div class="card">
        <img class="img-fluid w-120 h-90" id="normal_img3" src="/static/TubeTool.svg" alt="Card image cap">
      </div>
    </div>


  </div>

</div>

</main>


    <footer>
      <!-- Your footer content goes here -->
      <script src="/static/script.js"></script>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
  </body>
</html>